/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.movieticketbookingsystem;

import javax.swing.JOptionPane;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Noltan
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    
    private Admin admin;
    private Database database;
    public AdminDashboard(Admin admin, Database database) {
        initComponents();
        this.admin = admin;
        this.database = database;
        setLocationRelativeTo(null);
       
       welcomeLabel.setText("Welcome, " + admin.getFirstName() + " " + admin.getLastName() + "!");


    }
    
    private void switchPanel(JPanel panel) {
    mainContentPanel.removeAll();
    mainContentPanel.add(panel);
    mainContentPanel.revalidate();
    mainContentPanel.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        Buttons = new javax.swing.JPanel();
        addMovieButton = new javax.swing.JButton();
        showMoviesButton = new javax.swing.JButton();
        updateMovieButton = new javax.swing.JButton();
        showShowTimesButton = new javax.swing.JButton();
        deleteMovieButton = new javax.swing.JButton();
        updateShowTimeButton = new javax.swing.JButton();
        addShowTimeButton = new javax.swing.JButton();
        deleteShowTimeButton = new javax.swing.JButton();
        addAdminButton = new javax.swing.JButton();
        showBookingsButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        mainContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 37, 41));

        backgroundPanel.setBackground(new java.awt.Color(33, 37, 41));

        Buttons.setBackground(new java.awt.Color(33, 37, 41));
        Buttons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        addMovieButton.setBackground(new java.awt.Color(255, 193, 7));
        addMovieButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addMovieButton.setText("Add New Movie");
        addMovieButton.setBorder(null);
        addMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieButtonActionPerformed(evt);
            }
        });

        showMoviesButton.setBackground(new java.awt.Color(255, 193, 7));
        showMoviesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showMoviesButton.setText("Show Movie");
        showMoviesButton.setBorder(null);
        showMoviesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMoviesButtonActionPerformed(evt);
            }
        });

        updateMovieButton.setBackground(new java.awt.Color(255, 193, 7));
        updateMovieButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateMovieButton.setText("Update Movie");
        updateMovieButton.setBorder(null);
        updateMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMovieButtonActionPerformed(evt);
            }
        });

        showShowTimesButton.setBackground(new java.awt.Color(255, 193, 7));
        showShowTimesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showShowTimesButton.setText("Show Show Times");
        showShowTimesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showShowTimesButtonActionPerformed(evt);
            }
        });

        deleteMovieButton.setBackground(new java.awt.Color(255, 193, 7));
        deleteMovieButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteMovieButton.setText("Delete Movie");
        deleteMovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMovieButtonActionPerformed(evt);
            }
        });

        updateShowTimeButton.setBackground(new java.awt.Color(255, 193, 7));
        updateShowTimeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateShowTimeButton.setText("Update Show Time");
        updateShowTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateShowTimeButtonActionPerformed(evt);
            }
        });

        addShowTimeButton.setBackground(new java.awt.Color(255, 193, 7));
        addShowTimeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addShowTimeButton.setText("Add Show Time");
        addShowTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShowTimeButtonActionPerformed(evt);
            }
        });

        deleteShowTimeButton.setBackground(new java.awt.Color(255, 193, 7));
        deleteShowTimeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteShowTimeButton.setText("Delete Show Time");
        deleteShowTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteShowTimeButtonActionPerformed(evt);
            }
        });

        addAdminButton.setBackground(new java.awt.Color(255, 193, 7));
        addAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addAdminButton.setText("Add New Admin");
        addAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminButtonActionPerformed(evt);
            }
        });

        showBookingsButton.setBackground(new java.awt.Color(255, 193, 7));
        showBookingsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showBookingsButton.setText("Show Bookings");
        showBookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBookingsButtonActionPerformed(evt);
            }
        });

        quitButton.setBackground(new java.awt.Color(255, 193, 7));
        quitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quitButton.setText("Log Out");
        quitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 193, 7));
        jLabel1.setText("Admin Dashboard");

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(255, 193, 7));

        javax.swing.GroupLayout ButtonsLayout = new javax.swing.GroupLayout(Buttons);
        Buttons.setLayout(ButtonsLayout);
        ButtonsLayout.setHorizontalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonsLayout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jLabel1))
                        .addGroup(ButtonsLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(addMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showBookingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteShowTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateShowTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showShowTimesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addShowTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showMoviesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        ButtonsLayout.setVerticalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(showMoviesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(updateMovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(deleteMovieButton)
                .addGap(29, 29, 29)
                .addComponent(addShowTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(showShowTimesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(updateShowTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(deleteShowTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(addAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(showBookingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        mainContentPanel.setBackground(new java.awt.Color(33, 37, 41));
        mainContentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addComponent(Buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Buttons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminButtonActionPerformed
     
   switchPanel(new CreateAdminPanel(database));
  
    }//GEN-LAST:event_addAdminButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to Log out?");
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        dispose();
         new StartPage().setVisible(true);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void addMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieButtonActionPerformed
       switchPanel(new AddMoviePanel(database));
    }//GEN-LAST:event_addMovieButtonActionPerformed

    private void showMoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMoviesButtonActionPerformed
    switchPanel(new ShowMoviesPanel(database));
    }//GEN-LAST:event_showMoviesButtonActionPerformed

    private void updateMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMovieButtonActionPerformed
      switchPanel(new UpdateMoviePanel(database));
    }//GEN-LAST:event_updateMovieButtonActionPerformed

    private void deleteMovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMovieButtonActionPerformed
    switchPanel(new DeleteMoviePanel(database));
    }//GEN-LAST:event_deleteMovieButtonActionPerformed

    private void addShowTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShowTimeButtonActionPerformed
     switchPanel(new AddShowTimePanel(database));
    }//GEN-LAST:event_addShowTimeButtonActionPerformed

    private void updateShowTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateShowTimeButtonActionPerformed
       switchPanel(new UpdateShowTimePanel(database));
    }//GEN-LAST:event_updateShowTimeButtonActionPerformed

    private void deleteShowTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteShowTimeButtonActionPerformed
    switchPanel(new DeleteShowTimePanel(database));
    }//GEN-LAST:event_deleteShowTimeButtonActionPerformed

    private void showBookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBookingsButtonActionPerformed
     switchPanel(new ShowBookingsPanel(database));
    }//GEN-LAST:event_showBookingsButtonActionPerformed

    private void showShowTimesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showShowTimesButtonActionPerformed
       switchPanel(new ShowShowTimesPanel(database));
    }//GEN-LAST:event_showShowTimesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminDashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons;
    private javax.swing.JButton addAdminButton;
    private javax.swing.JButton addMovieButton;
    private javax.swing.JButton addShowTimeButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton deleteMovieButton;
    private javax.swing.JButton deleteShowTimeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton showBookingsButton;
    private javax.swing.JButton showMoviesButton;
    private javax.swing.JButton showShowTimesButton;
    private javax.swing.JButton updateMovieButton;
    private javax.swing.JButton updateShowTimeButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
