/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.movieticketbookingsystem;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Noltan
 */
public class DeleteMoviePanel extends javax.swing.JPanel {

    /**
     * Creates new form DeleteMoviePanel
     */
     private Database database;
    public DeleteMoviePanel(Database database) {
        initComponents();
        this.database = database;
        populateMovieComboBox();
    }
    
    private void populateMovieComboBox(){
        comboMovieIDs.removeAllItems();
        ArrayList<Movie> movies = MoviesDatabase.getAllMovies(database);
        
        for(Movie m : movies){
            comboMovieIDs.addItem(m.getID() + " - " + m.getName());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblSelectMovie = new javax.swing.JLabel();
        txtRunningTime = new javax.swing.JTextField();
        comboMovieIDs = new javax.swing.JComboBox<>();
        lblStarring = new javax.swing.JLabel();
        btnDeleteMovie = new javax.swing.JButton();
        txtStarring = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();
        txtLanguage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 37, 41));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Language:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Genre:");

        txtGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RunningTime:");

        lblSelectMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSelectMovie.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectMovie.setText("Select Movie ID");

        comboMovieIDs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie IDs" }));
        comboMovieIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovieIDsActionPerformed(evt);
            }
        });

        lblStarring.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStarring.setForeground(new java.awt.Color(255, 255, 255));
        lblStarring.setText("Starring:");

        btnDeleteMovie.setBackground(new java.awt.Color(255, 193, 7));
        btnDeleteMovie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteMovie.setText("Delete Movie");
        btnDeleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMovieActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rating:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 193, 7));
        jLabel6.setText("Delete Movie");

        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 193, 7));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblSelectMovie)
                    .addComponent(jLabel5)
                    .addComponent(lblStarring)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtName)
                        .addComponent(txtLanguage)
                        .addComponent(txtGenre)
                        .addComponent(txtRunningTime)
                        .addComponent(txtStarring)
                        .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboMovieIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMovieIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addComponent(txtRunningTime, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectMovie)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1)))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStarring, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStarring))
                        .addGap(36, 36, 36)
                        .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)))
                .addComponent(btnDeleteMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreActionPerformed
        // TODO add youstatusLabeling code here:
    }//GEN-LAST:event_txtGenreActionPerformed

    private void comboMovieIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovieIDsActionPerformed
        String selected = (String) comboMovieIDs.getSelectedItem();
        if(selected == null) return;

        int id = Integer.parseInt(selected.split(" - ")[0]);
        Movie movie = MoviesDatabase.getMovie(id, database);

        if(movie != null){
            txtName.setText(movie.getName());
            txtLanguage.setText(movie.getLanguage());
            txtGenre.setText(movie.getGenre());
            txtRunningTime.setText(String.valueOf(movie.getRunningTime()));
            txtStarring.setText(movie.getStarring());
            txtRating.setText(movie.getRating());
        }
    }//GEN-LAST:event_comboMovieIDsActionPerformed

    private void btnDeleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMovieActionPerformed
        String selected = (String) comboMovieIDs.getSelectedItem();
    if (selected == null) {
        statusLabel.setText("Please select a movie to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this movie?");
    if (confirm != JOptionPane.YES_OPTION) {
        statusLabel.setText("Movie deletion cancelled.");
        return;
    }

    int id = Integer.parseInt(selected.split(" - ")[0]);
    String deleteQuery = "DELETE FROM `movies` WHERE `ID` = " + id + ";";

    try {
        database.getStatement().execute(deleteQuery);
        statusLabel.setText("Movie deleted successfully.");
        populateMovieComboBox(); // Refresh list
    } catch (Exception e) {
        e.printStackTrace();
        statusLabel.setText("Error deleting movie.");
    }
    }//GEN-LAST:event_btnDeleteMovieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteMovie;
    private javax.swing.JComboBox<String> comboMovieIDs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblSelectMovie;
    private javax.swing.JLabel lblStarring;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtRunningTime;
    private javax.swing.JTextField txtStarring;
    // End of variables declaration//GEN-END:variables
}
