/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.movieticketbookingsystem;

import java.util.ArrayList;

/**
 *
 * @author Noltan
 */
public class ShowMoviesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowMoviesPanel
     */
    Database database;
    public ShowMoviesPanel(Database database) {
        initComponents();
          this.database = database;
        populateTable();
    }
     private void populateTable(){
        ArrayList<Movie> movies = MoviesDatabase.getAllMovies(database);
        
        String[] columnNames = {"ID", "Name", "Language", "Genre", "RunningTime", "Starring", "Rating"
        
    };
        
        Object[][] data = new Object[movies.size()][7];
        
        for(int i = 0; i < movies.size(); i++){
            Movie m = movies.get(i);
            data[i][0] = m.getID();
            data[i][1] = m.getName();
            data[i][2] = m.getLanguage();
            data[i][3] = m.getGenre();
            data[i][4] = m.getRunningTime();
            data[i][5] = m.getStarring();
            data[i][6] = m.getRating();
        }
        tableMovies.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        tableMovies = new javax.swing.JTable();

        setBackground(new java.awt.Color(33, 37, 41));

        scroll.setBackground(new java.awt.Color(33, 37, 41));

        tableMovies.setBackground(new java.awt.Color(255, 193, 7));
        tableMovies.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tableMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Langauge", "Genre", "RunningTime", "Starring", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scroll.setViewportView(tableMovies);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tableMovies;
    // End of variables declaration//GEN-END:variables
}
