/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.movieticketbookingsystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noltan
 */
public class ShowShowTimesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowShowTimesPanel
     */Database database;
   public ShowShowTimesPanel(Database database) {
        this.database = database;
        initComponents();
        loadMovieIDs();
    }
    
    private void loadMovieIDs(){
        try{
            comboMovie.removeAllItems();
            ResultSet rs = database.getStatement().executeQuery("SELECT ID, name FROM movies;");
            while(rs.next()){
                int id = rs.getInt("ID");
                String name = rs.getString("name");
              
                comboMovie.addItem(id + " - "+ name);
            }
            
            
        }catch (SQLException e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboMovie = new javax.swing.JComboBox<>();
        show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShowTimes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 37, 41));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Movie:");

        comboMovie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ShowTime ID" }));
        comboMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovieActionPerformed(evt);
            }
        });

        show.setBackground(new java.awt.Color(255, 193, 7));
        show.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        show.setText("Show ShowTimes");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        tableShowTimes.setBackground(new java.awt.Color(255, 193, 7));
        tableShowTimes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tableShowTimes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "ShowTime", "Capacity", "AvailableSeats", "Place"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableShowTimes);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 193, 7));
        jLabel2.setText("Show ShowTime");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel2)
                .addGap(0, 293, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(comboMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(show)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        String selected = (String) comboMovie.getSelectedItem();
        if (selected == null) return;

        String movieID = selected.split(" - ")[0];
        //    int movieID = Integer.parseInt(selected.split(" - ")[0]);
        try {
            String tableName = "movie " + movieID + " - shows";
            String query = "SELECT ID, showTime, capacity, availableSeats, place FROM `" + tableName + "`;";
            ResultSet rs = database.getStatement().executeQuery(query);

            DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Show Time", "Capacity", "Available Seats", "Place"}, 0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("ID"),
                    rs.getString("showTime"),
                    rs.getInt("capacity"),
                    rs.getInt("availableSeats"),
                    rs.getString("place")
                });
            }
            tableShowTimes.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_showActionPerformed

    private void comboMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMovieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboMovie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton show;
    private javax.swing.JTable tableShowTimes;
    // End of variables declaration//GEN-END:variables
}
