/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.movieticketbookingsystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Noltan
 */
public class UpdateMovieFrame extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMovieFrame
     */
    
    private Database database;
    public UpdateMovieFrame(Database database) {
        initComponents();
        this.database = database;
      populateMovieComboBox();
        
    }
    private void populateMovieComboBox(){
        ArrayList<Movie> movies = MoviesDatabase.getAllMovies(database);
        
        for(Movie m : movies){
            comboMovieIDs.addItem(String.valueOf(m.getID()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSelectMovie = new javax.swing.JLabel();
        comboMovieIDs = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        txtLanguage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtGenre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRunningTime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStarring = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        btnUpdateMovie = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbSelectMovie.setText("Select Movie ID:");

        comboMovieIDs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie list dropdown" }));
        comboMovieIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMovieIDsActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        lblLanguage.setText("Language:");

        jLabel1.setText("Genre:");
        jLabel1.setToolTipText("");

        jLabel2.setText("Running Time(min)");

        jLabel3.setText("Starring:");

        jLabel4.setText("Rating:");

        btnUpdateMovie.setText("Update Movie");
        btnUpdateMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMovieActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(lblLanguage)
                    .addComponent(lblName)
                    .addComponent(comboMovieIDs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSelectMovie)
                    .addComponent(txtName)
                    .addComponent(txtLanguage)
                    .addComponent(txtGenre)
                    .addComponent(txtRunningTime)
                    .addComponent(txtStarring)
                    .addComponent(btnUpdateMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRating, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbSelectMovie)
                .addGap(18, 18, 18)
                .addComponent(comboMovieIDs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtRunningTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtStarring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnUpdateMovie)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMovieActionPerformed
     int id = Integer.parseInt(comboMovieIDs.getSelectedItem().toString().split(" - ")[0]);
    Movie movie = new Movie();
    movie.setID(id);
    movie.setName(txtName.getText());
    movie.setLanguage(txtLanguage.getText());
    movie.setGenre(txtGenre.getText());
    movie.setRunningTime(Integer.parseInt(txtRunningTime.getText()));
    movie.setStarring(txtStarring.getText());
    movie.setRating(txtRating.getText());

    String update = "UPDATE `movies` SET `Name`='"+movie.getName()+"'," +
        "`Language`='"+movie.getLanguage()+"'," +
        "`Genre`='"+movie.getGenre()+"'," +
        "`RunningTime`='"+movie.getRunningTime()+"'," +
        "`Starring`='"+movie.getStarring()+"'," +
        "`Rating`='"+movie.getRating()+"' WHERE `ID` = "+movie.getID()+";";
    try {
        database.getStatement().execute(update);
        JOptionPane.showMessageDialog(null, "Movie updated successfully");
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnUpdateMovieActionPerformed

    private void comboMovieIDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMovieIDsActionPerformed
         String selected = (String) comboMovieIDs.getSelectedItem();
    int id = Integer.parseInt(selected.split(" - ")[0]);
    Movie movie = MoviesDatabase.getMovie(id, database);
    
    txtName.setText(movie.getName());
    txtLanguage.setText(movie.getLanguage());
    txtGenre.setText(movie.getGenre());
    txtRunningTime.setText(String.valueOf(movie.getRunningTime()));
    txtStarring.setText(movie.getStarring());
    txtRating.setText(movie.getRating());
    }//GEN-LAST:event_comboMovieIDsActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateMovieFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdateMovie;
    private javax.swing.JComboBox<String> comboMovieIDs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbSelectMovie;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtRunningTime;
    private javax.swing.JTextField txtStarring;
    // End of variables declaration//GEN-END:variables
}
