/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.movieticketbookingsystem;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

/**
 *
 * @author Noltan
 */
public class UpdateShowTimePanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateShowTimePanel
     */
      Database database;
    ArrayList<Movie> movies = new ArrayList<>();
    ArrayList<Show> shows = new ArrayList<>();


    public UpdateShowTimePanel(Database db) {
        initComponents();
        this.database = db;
        loadMovies();
        
       
    }

private void loadMovies() {
    movies = MoviesDatabase.getAllMovies(database);
    movieComboBox.removeAllItems();
    for (Movie m : movies) {
        movieComboBox.addItem(m.getID() + " - " + m.getName());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        movieComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();
        showComboBox = new javax.swing.JComboBox<>();
        statusLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        capacityField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        placeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 37, 41));

        updateButton.setBackground(new java.awt.Color(255, 193, 7));
        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateButton.setText("Update ShowTime");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Movie ID:");

        movieComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movie IDs" }));
        movieComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time(format: HH:mm):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Show ID:");

        timeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFieldActionPerformed(evt);
            }
        });

        showComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shows ID" }));
        showComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showComboBoxActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 193, 7));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date(format: yyyy-mm-dd):");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Capacity:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Place:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 193, 7));
        jLabel7.setText("Update ShowTime");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(movieComboBox, 0, 271, Short.MAX_VALUE)
                            .addComponent(showComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateField)
                            .addComponent(timeField)
                            .addComponent(capacityField)
                            .addComponent(placeField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel7)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(movieComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(capacityField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addComponent(updateButton)
                .addGap(35, 35, 35)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            int movieIndex = movieComboBox.getSelectedIndex();
            int showIndex = showComboBox.getSelectedIndex();
            if (movieIndex < 0 || showIndex < 0) {
                statusLabel.setText("Please select both movie and show.");
                return;
            }

            Movie movie = movies.get(movieIndex);
            Show show = shows.get(showIndex);

            String newDate = dateField.getText().trim();
            String newTime = timeField.getText().trim();
            int newCapacity = Integer.parseInt(capacityField.getText().trim());
            String place = placeField.getText().trim();

            String combinedDateTime = (newDate + " " + newTime).replaceAll(" +", " ");
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            LocalDateTime newShowTime = LocalDateTime.parse(combinedDateTime, formatter);

            int oldCapacity = show.getCapacity();
            int seatDiff = newCapacity - oldCapacity;
            int newAvailable = show.getAvailableSeats() + seatDiff;
            if (newAvailable < 0) {
                statusLabel.setText("Capacity too low. Not enough seats available.");
                return;
            }

            // Update local show object
            show.setShowTime(newShowTime);
            show.setCapacity(newCapacity);
            show.setAvailableSeats(newAvailable);
            show.setPlace(place);

            // SQL query
            String update = "UPDATE `movie " + movie.getID() + " - shows` SET "
            + "`showTime`='" + newDate + " " + newTime + "',"
            + "`capacity`='" + newCapacity + "',"
            + "`availableSeats`='" + newAvailable + "',"
            + "`place`='" + place + "' WHERE `ID` = " + show.getID() + " ;";

            database.getStatement().execute(update);
            statusLabel.setText("Show updated successfully!");
        } catch (Exception e) {
            e.printStackTrace();
            statusLabel.setText("Error updating show: " + e.getMessage());
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void movieComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieComboBoxActionPerformed
        int selectedIndex = movieComboBox.getSelectedIndex();
        if (selectedIndex >= 0) {
            Movie selectedMovie = movies.get(selectedIndex);
            shows = MoviesDatabase.getAllMovieShows(database, selectedMovie.getID());
            showComboBox.removeAllItems();
            for (Show show : shows) {
                showComboBox.addItem(String.valueOf(show.getID()));
            }
        }

    }//GEN-LAST:event_movieComboBoxActionPerformed

    private void timeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeFieldActionPerformed

    private void showComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showComboBoxActionPerformed
        int selectedIndex = showComboBox.getSelectedIndex();
        if (selectedIndex >= 0 && selectedIndex < shows.size()) {
            Show show = shows.get(selectedIndex);
            dateField.setText(show.getDate());
            timeField.setText(show.getTime());
            capacityField.setText(String.valueOf(show.getCapacity()));
            placeField.setText(show.getPlace());
        }
    }//GEN-LAST:event_showComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capacityField;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> movieComboBox;
    private javax.swing.JTextField placeField;
    private javax.swing.JComboBox<String> showComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField timeField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
